spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_management
    username: yasmine
    password: yasmine
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgresSQLDialect  # Corrected dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: localhost
    port: 1025
    username: postgres
    password: root
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 24 hours in milliseconds
      refresh-token:
        expiration: 604800000 # 7 days in milliseconds
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      photos-output-path: ./uploads
server:
  port: 8080